### ISSUE TITLE
Independent Tab Bar

### ISSUE THREAD

**Issue by BrandonKMLee** [pengx17/logseq-plugin-tabs#99]
Currently the Tab Bar is an overlay of the page, and that when scrolling the text underneath and between the tab buttons would hint through. Could the tab bar (not just the tab buttons) have non-transparent background?

**Comment by topherhunt** [comment]
I suspect this would be an easy fix (if pengx17 agrees that it's a desireable one; I'm unsure how many users would +1 this) but note that it's also easy to work around this by enabling CSS support in the plugin, then add a background style to the tab bar:

```
.logseq-tab-wrapper { background: #fff; }
```

**Comment by Tamriel** [comment]
Or, to be independent of the current theme:
```
#main-content-container {
  margin-top: 3.2rem;
}

```

**Comment by neolight1010** [comment]
@Tamriel's solution worked great for me! I added a line to have a line separator, for visual aid:

<img width="583" height="133" alt="Image" src="https://github.com/user-attachments/assets/9584cf40-f942-4450-a238-7cb3855beb05" />

```css
#main-content-container {
  margin-top: 2rem;
  border-top: 1px solid;
}
```

Update: For some reason the plugin/custom-CSS? causes additional padding to appear on the main content. I fixed it like this:

```css
#main-content-container > div {
  padding-top: 1.5rem;
}
```
